on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: Build
        run: ./gradlew clean build